[versions]
kotlin = "1.9.24"
androidGradlePlugin = "8.3.0"
downloadPlugin = "4.1.2"

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
download = { id = "de.undercouch.download", version.ref = "downloadPlugin" }
